package ru.geekbrains.java4.lesson6.db.model;

public class Products {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.id
     *
     * @mbggenerated Sat Jan 15 00:16:28 YEKT 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.title
     *
     * @mbggenerated Sat Jan 15 00:16:28 YEKT 2022
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.price
     *
     * @mbggenerated Sat Jan 15 00:16:28 YEKT 2022
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.category_id
     *
     * @mbggenerated Sat Jan 15 00:16:28 YEKT 2022
     */
    private Long category_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.id
     *
     * @return the value of products.id
     *
     * @mbggenerated Sat Jan 15 00:16:28 YEKT 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.id
     *
     * @param id the value for products.id
     *
     * @mbggenerated Sat Jan 15 00:16:28 YEKT 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.title
     *
     * @return the value of products.title
     *
     * @mbggenerated Sat Jan 15 00:16:28 YEKT 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.title
     *
     * @param title the value for products.title
     *
     * @mbggenerated Sat Jan 15 00:16:28 YEKT 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.price
     *
     * @return the value of products.price
     *
     * @mbggenerated Sat Jan 15 00:16:28 YEKT 2022
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.price
     *
     * @param price the value for products.price
     *
     * @mbggenerated Sat Jan 15 00:16:28 YEKT 2022
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.category_id
     *
     * @return the value of products.category_id
     *
     * @mbggenerated Sat Jan 15 00:16:28 YEKT 2022
     */
    public Long getCategory_id() {
        return category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.category_id
     *
     * @param category_id the value for products.category_id
     *
     * @mbggenerated Sat Jan 15 00:16:28 YEKT 2022
     */
    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }
}